[project]
name = "vrdformer-vrd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.5.1",
    "torchvision>=0.20.1",
]

[tool.uv.extra-build-dependencies]
lap = ["setuptools"]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu121"
